name: Andrew Der
favicon: null
layout_spectrum: 0.75926
typography_spectrum: 0.32314
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#808080'
    - '#ffffff'
    - '#a3008d'
    - '#0065ac'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
