name: Andrew Der
favicon: null
layout_spectrum: 0.75926
typography_spectrum: 0.32314
title: Andrew Der
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#666661'
    - '#dfdede'
    - '#3e3d3a'
    - '#a3a2a1'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
