name: AndrewDer
favicon: null
layout_spectrum: 0.14477308746427298
typography_spectrum: 0.06777086458168924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.829837211407721
  lightness: 0.9253799356520176
  saturation: 0.6361017287708819
  rhythmicContrast: 0.013887385837733746
purpose: []
